[package]
name = "tower-redis"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
tokio-sync = "0.1"
tower-service = "0.2"
redis-async = "0.4.4"
