[package]
name = "tower-mysql"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
async-lease = "0.1"
tower-service = "0.2"
mysql_async = "0.17.2"
