[package]
name = "tower-tiberius"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
tokio-sync = "0.1"
futures-state-stream = "0.1"
tower-service = "0.2"
tiberius = "0.3.1"
